'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NFsE_Santos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://producao.ginfes.com.br", ConfigurationName:="NFsE_Santos.ServiceGinfesImpl")>  _
    Public Interface ServiceGinfesImpl
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function CancelarNfse(ByVal arg0 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function CancelarNfseV3(ByVal arg0 As String, ByVal arg1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function ConsultarLoteRps(ByVal arg0 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function ConsultarLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function ConsultarNfse(ByVal arg0 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function ConsultarNfsePorRps(ByVal arg0 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function ConsultarNfsePorRpsV3(ByVal arg0 As String, ByVal arg1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function ConsultarNfseV3(ByVal arg0 As String, ByVal arg1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function ConsultarSituacaoLoteRps(ByVal arg0 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function ConsultarSituacaoLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function RecepcionarLoteRps(ByVal arg0 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.DataContractFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc)>  _
        Function RecepcionarLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceGinfesImplChannel
        Inherits NFsE_Santos.ServiceGinfesImpl, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceGinfesImplClient
        Inherits System.ServiceModel.ClientBase(Of NFsE_Santos.ServiceGinfesImpl)
        Implements NFsE_Santos.ServiceGinfesImpl
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CancelarNfse(ByVal arg0 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.CancelarNfse
            Return MyBase.Channel.CancelarNfse(arg0)
        End Function
        
        Public Function CancelarNfseV3(ByVal arg0 As String, ByVal arg1 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.CancelarNfseV3
            Return MyBase.Channel.CancelarNfseV3(arg0, arg1)
        End Function
        
        Public Function ConsultarLoteRps(ByVal arg0 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.ConsultarLoteRps
            Return MyBase.Channel.ConsultarLoteRps(arg0)
        End Function
        
        Public Function ConsultarLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.ConsultarLoteRpsV3
            Return MyBase.Channel.ConsultarLoteRpsV3(arg0, arg1)
        End Function
        
        Public Function ConsultarNfse(ByVal arg0 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.ConsultarNfse
            Return MyBase.Channel.ConsultarNfse(arg0)
        End Function
        
        Public Function ConsultarNfsePorRps(ByVal arg0 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.ConsultarNfsePorRps
            Return MyBase.Channel.ConsultarNfsePorRps(arg0)
        End Function
        
        Public Function ConsultarNfsePorRpsV3(ByVal arg0 As String, ByVal arg1 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.ConsultarNfsePorRpsV3
            Return MyBase.Channel.ConsultarNfsePorRpsV3(arg0, arg1)
        End Function
        
        Public Function ConsultarNfseV3(ByVal arg0 As String, ByVal arg1 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.ConsultarNfseV3
            Return MyBase.Channel.ConsultarNfseV3(arg0, arg1)
        End Function
        
        Public Function ConsultarSituacaoLoteRps(ByVal arg0 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.ConsultarSituacaoLoteRps
            Return MyBase.Channel.ConsultarSituacaoLoteRps(arg0)
        End Function
        
        Public Function ConsultarSituacaoLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.ConsultarSituacaoLoteRpsV3
            Return MyBase.Channel.ConsultarSituacaoLoteRpsV3(arg0, arg1)
        End Function
        
        Public Function RecepcionarLoteRps(ByVal arg0 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.RecepcionarLoteRps
            Return MyBase.Channel.RecepcionarLoteRps(arg0)
        End Function
        
        Public Function RecepcionarLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As String Implements NFsE_Santos.ServiceGinfesImpl.RecepcionarLoteRpsV3
            Return MyBase.Channel.RecepcionarLoteRpsV3(arg0, arg1)
        End Function
    End Class
End Namespace
