'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CadastroCotacao

    '''<summary>
    '''Button5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''updPainel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPainel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtcnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcnpj As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divsuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divsuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmsgSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsgSuccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''diverro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents diverro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmsgErro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsgErro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divinfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmsginfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsginfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNumeroCotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroCotacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckbLTL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbLTL As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckbDtaHub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbDtaHub As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckbTranspDedicado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbTranspDedicado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDataFollowUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataFollowUp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAbertura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbertura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtViaTransporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViaTransporte As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlServico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlServico As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEstufagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstufagem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIncoterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIncoterm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ckbFreeHand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbFreeHand As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlAnalista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAnalista As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtValidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValidade As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlStatusCotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatusCotacao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlUsuarioStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUsuarioStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDataStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEnvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlStatusFreteAgente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatusFreteAgente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoBL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDestinatarioComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDestinatarioComercial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodTranspRodoviario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodTranspRodoviario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNomeTranspRodoviario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeTranspRodoviario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTranspRodoviario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTranspRodoviario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodExportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodExportador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNomeExportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeExportador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlExportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExportador As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodIndicador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodIndicador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNomeIndicador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeIndicador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlIndicador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIndicador As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodAgente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodAgente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNomeAgente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeAgente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAgente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAgente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodImportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodImportador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNomeImportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeImportador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlImportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlImportador As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNomeCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCliente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlContato As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divClienteFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divClienteFinal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlClienteFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClienteFinal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtID_Vendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID_Vendedor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVendedor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProcessoCotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProcessoCotacao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataCalculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataCalculo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCalcular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalcular As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlMotivoCancelamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMotivoCancelamento As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtObsCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObsCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtObsOperacional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObsOperacional As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtObsCancelamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObsCancelamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGravar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''mpeNovoFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeNovoFrete As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divSuccessFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuccessFrete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmsgSuccessNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsgSuccessNovo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divErroFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divErroFrete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblErroFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErroFrete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divInfoFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divInfoFrete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblInfoFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoFrete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCodTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodTransportador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNomeTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeTransportador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTransportadorFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTransportadorFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblorigem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblorigem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlOrigemFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrigemFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbldestino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldestino As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDestinoFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDestinoFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlFreteTransportador_Frete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFreteTransportador_Frete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoPagamento_Frete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoPagamento_Frete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoCargaFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoCargaFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRotaFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRotaFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divEscala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEscala As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlEscala1Frete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEscala1Frete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEscala2Frete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEscala2Frete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEscala3Frete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEscala3Frete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTTimeFreteInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTimeFreteInicial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTTimeFreteFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTimeFreteFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTTimeFreteMedia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTimeFreteMedia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divTTAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTTAereo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtTTimeFreteTruckingAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTimeFreteTruckingAereo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlFrequenciaFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFrequenciaFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtValorFrequenciaFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorFrequenciaFrete As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPesoTaxadoFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoTaxadoFrete As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlEstufagemFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstufagemFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDivisaoProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDivisaoProfit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtValorDivisaoProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorDivisaoProfit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlMoedaFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMoedaFrete As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divFreteCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFreteCompra As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFreteCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreteCompra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divFreteVenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFreteVenda As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFreteVenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreteVenda As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlFinalDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFinalDestination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divCheckFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCheckFrete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ckFreteDeclarado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckFreteDeclarado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckFreteProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckFreteProfit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divMinimosFCL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMinimosFCL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCompraMinimaFCL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompraMinimaFCL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVendaMinimaFCL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVendaMinimaFCL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIncludedFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncludedFrete As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSalvarFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarFrete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFecharFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFecharFrete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNovoFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovoFrete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divCadErroFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCadErroFrete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblErrocadFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrocadFrete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divDeleteErroFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDeleteErroFrete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDeleteErroFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteErroFrete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgvFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvFrete As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''mpeNovoMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeNovoMercadoria As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divSuccessMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuccessMercadoria As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSuccessMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessMercadoria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divErroMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divErroMercadoria As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblErroMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErroMercadoria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIDMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCotacaoMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCotacaoMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMercadoria As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divCntr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCntr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RedContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedContainer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipoContainerMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoContainerMercadoria As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RedQTDContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedQTDContainer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQtdContainerMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdContainerMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divQtdMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divQtdMercadoria As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RedQTDMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedQTDMercadoria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQtdMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DivFreetime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivFreetime As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RedFree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedFree As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFreeTimeMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreeTimeMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFreteCompraMercadoriaUnitario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreteCompraMercadoriaUnitario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFreteCompraMercadoriaCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreteCompraMercadoriaCalc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divCompraMinimaLCL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCompraMinimaLCL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFreteCompraMinima control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreteCompraMinima As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFreteVendaMercadoriaUnitario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreteVendaMercadoriaUnitario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFreteVendaMercadoriaCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreteVendaMercadoriaCalc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divVendaMinimaLCL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divVendaMinimaLCL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFreteVendaMinima control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreteVendaMinima As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RedPesoBruto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedPesoBruto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPesoBrutoMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesoBrutoMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RedM3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedM3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtM3Mercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM3Mercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''Controle txtPesoTaxadoMercadoria.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''txtPesoTaxadoMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents txtPesoTaxadoMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''Controle txtValorCargaMercadoria.
=======
    '''txtValorCargaMercadoria control.
>>>>>>> master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorCargaMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMoedaCarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMoedaCarga As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
<<<<<<< HEAD
    '''Controle divMedidasMaritimo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''divMedidasMaritimo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents divMedidasMaritimo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
<<<<<<< HEAD
    '''Controle txtComprimentoMercadoria.
=======
    '''txtComprimentoMercadoria control.
>>>>>>> master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComprimentoMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLarguraMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLarguraMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAlturaMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlturaMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''Controle divMedidasAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''divMedidasAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents divMedidasAereo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
<<<<<<< HEAD
    '''Controle txtQtdCaixasAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''txtQtdCaixasAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents txtQtdCaixasAereo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''Controle txtComprimentoMercadoriaAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''txtComprimentoMercadoriaAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents txtComprimentoMercadoriaAereo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''Controle txtLarguraMercadoriaAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''txtLarguraMercadoriaAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents txtLarguraMercadoriaAereo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''Controle txtAlturaMercadoriaAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''txtAlturaMercadoriaAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents txtAlturaMercadoriaAereo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
<<<<<<< HEAD
    '''Controle btnAdicionarMedidasAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents btnAdicionarMedidasAereo As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Controle dgvMedidasAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents dgvMedidasAereo As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Controle divTesteMedidasAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents divTesteMedidasAereo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Controle TextBox5.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents TextBox5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controle TextBox6.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents TextBox6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controle TextBox7.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents TextBox7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controle TextBox8.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents TextBox8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Controle ImageButton2.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
    '''</remarks>
    Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Controle txtDsMercadoria.
=======
    '''btnAdicionarMedidasAereo control.
>>>>>>> master
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdicionarMedidasAereo As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''dgvMedidasAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvMedidasAereo As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divTesteMedidasAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTesteMedidasAereo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TextBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ImageButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtDsMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDsMercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOBS_Endereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOBS_Endereco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOutrasOBS_Mercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOutrasOBS_Mercadoria As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSalvarMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarMercadoria As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFecharMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFecharMercadoria As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNovaMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovaMercadoria As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divDeleteMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDeleteMercadoria As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDeleteMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteMercadoria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divDeleteErroMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDeleteErroMercadoria As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDeleteErroMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteErroMercadoria As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgvMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvMercadoria As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''mpeNovoTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeNovoTaxa As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divSuccessTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuccessTaxa As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblsuccessTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsuccessTaxa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divErroTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divErroTaxa As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblErroTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErroTaxa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIDTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIDTaxa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCotacaoTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCotacaoTaxa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlItemDespesaTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlItemDespesaTaxa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ckbDeclaradoTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbDeclaradoTaxa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckbProfitTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbProfitTaxa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlDestinatarioCobrancaTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDestinatarioCobrancaTaxa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlFornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFornecedor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlBaseCalculoTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBaseCalculoTaxa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQtdBaseCalculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdBaseCalculo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTipoPagamentoTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoPagamentoTaxa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlOrigemPagamentoTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrigemPagamentoTaxa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RedMoedaCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedMoedaCompra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMoedaCompraTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMoedaCompraTaxa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RedValorTaxaCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RedValorTaxaCompra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtValorTaxaCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorTaxaCompra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtValorTaxaCompraMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorTaxaCompraMin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtValorTaxaCompraCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorTaxaCompraCalc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlMoedaVendaTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMoedaVendaTaxa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtValorTaxaVenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorTaxaVenda As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtValorTaxaVendaMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorTaxaVendaMin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtValorTaxaVendaCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorTaxaVendaCalc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtObsTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObsTaxa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSalvarTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarTaxa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFecharTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFecharTaxa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNovaTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovaTaxa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnImportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImportar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSelecionarTudo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSelecionarTudo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeletarTaxas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletarTaxas As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divDeleteTaxas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDeleteTaxas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDeleteTaxas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteTaxas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divDeleteErroTaxas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDeleteErroTaxas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDeleteErroTaxas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteErroTaxas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgvTaxas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvTaxas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtQtd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel7 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvHistoricoCotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvHistoricoCotacao As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''UpdatePanel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel8 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvHistoricoFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvHistoricoFrete As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''UpdatePanel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel11 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''divSuccessReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSuccessReferencia As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSuccessReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessReferencia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divErroReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divErroReferencia As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblErroReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErroReferencia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipoReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoReferencia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGravarReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGravarReferencia As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLimparReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimparReferencia As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtID_Referencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID_Referencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''div10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dgvReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvReferencia As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dsReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReferencia As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCotacao As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsMoeda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsMoeda As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsPorto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsPorto As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsComex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsComex As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsRota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRota As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTransportador As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsAgente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAgente As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsIndicador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsIndicador As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsExportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsExportador As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsFrequencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFrequencia As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCarga As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContainer As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsMercadoria As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsEstufagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsEstufagem As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsStatusCotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsStatusCotacao As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsDestinatarioComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDestinatarioComercial As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsIncoterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsIncoterm As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsUsuario As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsClienteFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsClienteFinal As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCliente As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsImportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsImportador As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsContato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContato As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsVendedor As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsMotivoCancelamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsMotivoCancelamento As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsServico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsServico As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsBL As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsMercadorias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsMercadorias As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsIDMercadoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsIDMercadoria As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsFreteTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFreteTransportador As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsTaxas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTaxas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsOrigemPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsOrigemPagamento As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsDestinatarioCobranca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDestinatarioCobranca As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsHistoricoCotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsHistoricoCotacao As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsFornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFornecedor As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsBaseCalculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsBaseCalculo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsDivisaoProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDivisaoProfit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsItemDespesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsItemDespesa As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsTipoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTipoPagamento As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsStatusFreteAgente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsStatusFreteAgente As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsHistoricoFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsHistoricoFrete As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsFinalDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFinalDestination As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsRodoviario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRodoviario As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
<<<<<<< HEAD
    '''Controle SqlDataSource1.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
<<<<<<< HEAD
    '''Controle dsMedidasAereo.
    '''</summary>
    '''<remarks>
    '''Campo gerado automaticamente.
    '''Modificar a declaração do campo de movimento do arquivo de designer para o arquivo code-behind.
=======
    '''dsMedidasAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
>>>>>>> master
    '''</remarks>
    Protected WithEvents dsMedidasAereo As Global.System.Web.UI.WebControls.SqlDataSource
End Class
