
Public Class _Default
    Inherits Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Load

        '        Dim SQL As String = "SELECT 
        'CASE WHEN GRAU ='M' THEN 'MBL' ELSE NR_PROCESSO END 'OUR REFERENCE' ,
        'PARCEIRO_CLIENTE AS CUSTOMER,
        'DT_EMBARQUE AS DEPARTURE ,
        'DT_CHEGADA AS ARRIVAL,
        'TP_VIA_INGLES AS 'AIR/SEA',
        'TP_SERVICO AS 'IMP/EXP',
        'ORIGEM AS ORIGIN,
        'DESTINO AS DESTIN,
        '(SELECT CD_TIPO_PAGAMENTO FROM TB_TIPO_PAGAMENTO WHERE ID_TIPO_PAGAMENTO = A.ID_TIPO_PAGAMENTO_MASTER)'P/C MBL'	,
        'NR_BL_MASTER AS 'Nº MASTER',
        '(SELECT CD_TIPO_PAGAMENTO FROM TB_TIPO_PAGAMENTO WHERE ID_TIPO_PAGAMENTO = A.ID_TIPO_PAGAMENTO)'P/C HBL',
        'NR_BL AS 'Nº HOUSE',
        'B.NR_INVOICE INVOICE,
        'DT_INVOICE DATE,
        'CD_ACCOUNT_TIPO_FATURA 'CN/DN',
        'SIGLA_MOEDA CURR,
        'SUM(ISNULL(VL_TAXA,0))TOTAL
        ' FROM [dbo].[View_BL]  A 
        ' INNER JOIN (SELECT * FROM FN_ACCOUNT_INVOICE('01/01/2021','01/01/2022')) AS B ON B.ID_BL_INVOICE = A.ID_BL
        ' WHERE FL_CONFERIDO = 1 GROUP BY B.ID_ACCOUNT_INVOICE,B.NR_INVOICE,ORIGEM,DESTINO,NR_BL,GRAU,DT_EMBARQUE,DT_CHEGADA,PARCEIRO_CLIENTE,DT_INVOICE,SIGLA_MOEDA,CD_ACCOUNT_TIPO_FATURA,NR_PROCESSO,TIPO_PAGAMENTO,NR_BL_MASTER,TP_SERVICO,TP_VIA_INGLES,ID_TIPO_PAGAMENTO_MASTER,ID_TIPO_PAGAMENTO"


        '        Classes.Excel.exportaExcel(SQL, "NVOCC", "SOA")
    End Sub


End Class