'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster

    '''<summary>
    '''navbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents navbar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MenuCadastros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuCadastros As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MenuUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuUsuario As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnGruposUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnGruposUsuarios As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnPermissoesUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnPermissoesUsuarios As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnUsuarios As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MenuParceiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuParceiro As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnParceirosConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnParceirosConsulta As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnParceiros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnParceiros As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnEmailParceiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnEmailParceiro As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnMoedaFrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnMoedaFrete As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnMoedaFreteArmador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnMoedaFreteArmador As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnItemDespesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnItemDespesa As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MenuComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuComercial As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnFreteTransportador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnFreteTransportador As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnCotacaoComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnCotacaoComercial As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A15 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnComissaoVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnComissaoVendedor As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MenuOperacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuOperacao As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnModuloOperacional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnModuloOperacional As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnConsultarWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnConsultarWeek As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnCourrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnCourrier As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MenuFinanceiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuFinanceiro As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnFinanceiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnFinanceiro As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnModuloDemurrage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnModuloDemurrage As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnAccount As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnFechamentoCambio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnFechamentoCambio As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A11 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnComissaoIndicadorNacional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnComissaoIndicadorNacional As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnComissaoIndicadorInternacional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnComissaoIndicadorInternacional As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnFaturamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnFaturamento As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A12 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A14 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A16 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mnModuloGerencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnModuloGerencial As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A22 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A23 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A24 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbllogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllogin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mnTrocaPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnTrocaPerfil As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scripts As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
