Public Class Consignee
    Public Property name As String
    Public Property code As String
    Public Property region As String
    Public Property city As String
    Public Property address As String
    Public Property address_complement As String
    Public Property zip_code As String
    Public Property number As String
    Public Property phone As String
    Public Property email As String
    Public Property activity As String
    Public Property legal_nature As String
    Public Property type As String
    Public Property type_title As String
    Public Property vessel_imo As String
    Public Property vessel_name As String
    Public Property voyage_number As String
    Public Property manufacture_country_name As String
    Public Property manufacture_country_siscomex_code As String
    Public Property manufacture_country As String
    Public Property origin_country As String
    Public Property origin_country_code_siscomex As String
    Public Property destination_country As String
    Public Property destination_country_code_siscomex As String
    Public Property origin_port As String
    Public Property origin_port_code As String
    Public Property lading_port As String
    Public Property landing_port_code As String
    Public Property unlading_port As String
    Public Property unlading_port_code As String
    Public Property destination_port As String
    Public Property destination_port_code As String
    Public Property lading_terminal As String
    Public Property landing_terminal As String
    Public Property container_type As String
    Public Property containers As String
    Public Property obs_notes As String
    Public Property freight_currency As String
    Public Property payment_type As String
End Class
